### ISSUE TITLE
nothing is displayed when bookmarks don't have name

### ISSUE THREAD

**Issue by odmishien** [julianpierer/duree#2]
Hi. 
I'd like to use duree on Chrome, but nothing is displayed.

![スクリーンショット 2020-07-28 12 27 51](https://user-images.githubusercontent.com/25533384/88615963-eb227b00-d0cd-11ea-803d-ec9c630f2a78.png)

Maybe the cause is that I don't set the name of bookmarks like above image.(It's simple)
So, can I make pull request which add feature that work correctly in such a situation?
or, I'd like to hear your opinion @julianpierer

**Comment by julianpierer** [comment]
Hey @odmishien 
duree uses the bookmark name as the title, which is empty in your case.
What should be displayed in your case?

**Comment by odmishien** [comment]
Thanks for the reply.
In my opinion, only favicons are displayed if bookmarks don't have any name.
